name: Push to DockerHub

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 UTC every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: danielmichaels
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      run: |
        ./scripts/build_and_push